CREATE TABLE [usuario](
  ID INT NOT NULL UNIQUE, 
  USERNAME VARCHAR(150) NOT NULL, 
  EMAIL VARCHAR(150) NOT NULL, 
  PASSWORD VARCHAR(20) NOT NULL);


CREATE TABLE cliente(
  ID INT NOT NULL UNIQUE, 
  DATA_CADASTRO TIMESTAMP,
  NOME VARCHAR(150), 
  ENDERECO VARCHAR(150), 
  CIDADE VARCHAR(150), 
  UF CHAR(2),
  CEP VARCHAR(10), 
  TELEFONE VARCHAR(150) 
  );